default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: skeleton
  password: skeleton
  port: 5432

development:
  <<: *default
  database: skeleton-dev

test:
  <<: *default
  database: skeleton-test

production:
  <<: *default
  database: skeleton_production
