default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: starter-kit
  password: starter-kit
  port: 5432

development:
  <<: *default
  database: starter-kit-dev

test:
  <<: *default
  database: starter-kit-test

production:
  <<: *default
  database: starter-kit_production
